# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrap Caged Tabela 6

on:
  workflow_dispatch:

jobs:
  importar_libs:

    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install lib pandas
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Install lib numpy
      run: pip install numpy
    - name: Install lib datetime
      run: pip install datetime
    - name: Install lib requests
      run: pip install requests
    - name: Install lib bs4
      run: pip install bs4
    - name: Install lib botocore
      run: pip install botocore    
    - name: Install lib boto3
      run: pip install boto3  
    - name: Install lib openpyxl
      run: pip install openpyxl
  
  scrap_tabela_caged:
    runs-on: ubuntu-latest
    steps:
      - name: Executar scrap da tabela 6 no caged
        run: |
          python caged_tab6.py
          pwd;ls -l
      - name: Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
        #role-to-assume: arn:aws:iam::143390484559:role/caged_action
            role-to-assume: arn:aws:iam::143390484559:role/github-actions-role
            aws-region: ${{env.AWS_DEFAULT_REGION}}
      
    #- name: Checkout
    #  uses: actions/checkout@v2
      
  AWS_Command:
    runs-on: ubuntu-lastest
    steps:
    - name: Copiar tabela para o bucket
      run: |
        pwd;ls;aws s3 cp df_caged_tab6_092022.csv s3://s3-caged
      
    #- uses: actions/upload-artifact@v2
    #  with:
    #       name: df_caged_tab6_092022.csv
    #       path: .
        
  #download_file:
  #  name: Download File
  #  runs-on: ubuntu-latest
  #  needs: get_libs_and_table
 #  steps:
 #     - uses: actions/download-artifact@v2
 #       with:
 #          name: df_caged_tab6_092022.csv
 #          path: .
 #     - name: Display files
 #       run: pwd;ls -l;cat df_caged_tab6_092022.csv    
  
    
         
  
  
       
